(function bootCommunicationApp(){
  'use strict';
  const $=id=>document.getElementById(id);
  const state={client:null,profile:null,capabilities:{view:false,create_notice:false,create_meeting:false,meeting_types:[]},roles:[],users:[],items:[],view:'notices',calendar:new Date(),pendingOnly:false,loading:true,modal:null,previousFocus:null,clock:null};
  const meta={aviso:{label:'Aviso',icon:'!'},reuniao:{label:'Reunião',icon:'R'},treinamento:{label:'Treinamento',icon:'T'}};
  const statusLabels={agendada:'Agendada',concluida:'Concluída',cancelada:'Cancelada'};

  function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=String(text);return el}
  function rows(value){if(Array.isArray(value))return value;if(Array.isArray(value?.items))return value.items;return value?[value]:[]}
  function safeMessage(error,fallback){console.error('[comunicacao]',error);return window.SuperAppAuth?.getSafeAuthMessage?.(error,fallback)||fallback}
  async function rpc(name,params){const {data,error}=await state.client.rpc(name,params||{});if(error)throw error;return data}
  function toast(message,type){const el=$('toast');el.textContent=message;el.className='toast show'+(type?' '+type:'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>{el.className='toast'},3400)}
  function dateValue(value){const date=value?new Date(value):null;return date&&!Number.isNaN(date.getTime())?date:null}
  function sameDay(a,b){return a&&b&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
  function formatDate(value,withTime=true){const date=dateValue(value);if(!date)return 'Data não informada';return new Intl.DateTimeFormat('pt-BR',withTime?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'long'}).format(date)}
  function formatCreated(value){const date=dateValue(value);return date?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(date):''}
  function safeHttpUrl(value){if(!value)return null;try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:null}catch(_){return null}}
  function roleScope(profile){if(profile?.franchise_name)return 'Franquia · '+profile.franchise_name;if(profile?.unit_name)return 'Matriz · '+profile.unit_name;return 'Matriz · acesso global'}
  function localParts(value){const date=dateValue(value);if(!date)return{date:'',time:''};return{date:[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-'),time:String(date.getHours()).padStart(2,'0')+':'+String(date.getMinutes()).padStart(2,'0')}}
  function audienceLabel(item){if(item.type==='reuniao'){const names=rows(item.assigned_user_names);return names.length?names.length+' participante'+(names.length===1?'':'s'):'Reunião geral'}const codes=rows(item.audience_roles);return codes.length?codes.map(code=>state.roles.find(role=>role.code===code)?.display_name||code).join(', '):'Todos os cargos'}

  function applyTheme(theme,persist=true){const normalized=theme==='dark'?'dark':'light';document.documentElement.dataset.theme=normalized;const toggle=$('theme-toggle'),knob=toggle?.querySelector('.knob');if(knob)knob.textContent=normalized==='dark'?'🌙':'☀️';if(toggle){toggle.setAttribute('aria-pressed',String(normalized==='dark'));toggle.setAttribute('aria-label',normalized==='dark'?'Ativar modo claro':'Ativar modo escuro')}if(persist){try{localStorage.setItem('321modular_theme',normalized)}catch(_){}}}
  function closeMenu(){$('aside')?.classList.remove('aside-open');$('aside-backdrop')?.classList.remove('active');$('menu-btn')?.setAttribute('aria-expanded','false')}
  function setupShell(){
    $('menu-btn').addEventListener('click',()=>{const open=$('aside').classList.toggle('aside-open');$('aside-backdrop').classList.toggle('active',open);$('menu-btn').setAttribute('aria-expanded',String(open))});
    $('aside-backdrop').addEventListener('click',closeMenu);$('theme-toggle').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
    $('logout-btn').addEventListener('click',()=>{location.href=window.SuperAppAuth.getPortalUrl()});$('refresh-btn').addEventListener('click',loadItems);
    $('new-notice-btn').addEventListener('click',()=>openEditor(null,'notice'));$('new-meeting-btn').addEventListener('click',()=>openEditor(null,'meeting'));
    document.querySelectorAll('#nav-tabs [data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
    window.addEventListener('resize',()=>{if(innerWidth>880)closeMenu()});window.addEventListener('storage',event=>{if(event.key==='321modular_theme')applyTheme(event.newValue||'light',false)});applyTheme(document.documentElement.dataset.theme||'light',false);
  }
  function setView(view){state.view=['notices','meetings','calendar'].includes(view)?view:'notices';const labels={notices:['Avisos','Comunicados destinados aos cargos selecionados.'],meetings:['Reuniões','Reuniões e treinamentos agendados.'],calendar:['Calendário','Consulte as reuniões e treinamentos de cada dia.']};document.querySelectorAll('#nav-tabs [data-view]').forEach(button=>{const active=button.dataset.view===state.view;button.classList.toggle('active',active);button.toggleAttribute('aria-current',active)});$('view-title').textContent=labels[state.view][0];$('view-subtitle').textContent=labels[state.view][1];$('new-notice-btn').hidden=state.view!=='notices'||!state.capabilities.create_notice;$('new-meeting-btn').hidden=state.view==='notices'||!state.capabilities.create_meeting;closeMenu();renderView()}

  function setupModals(){
    $('editor-close').addEventListener('click',closeEditor);$('cancel-btn').addEventListener('click',closeEditor);$('editor-modal').addEventListener('mousedown',event=>{if(event.target===$('editor-modal'))closeEditor()});
    $('day-close').addEventListener('click',closeDay);$('day-done').addEventListener('click',closeDay);$('day-modal').addEventListener('mousedown',event=>{if(event.target===$('day-modal'))closeDay()});
    $('type-input').addEventListener('change',syncEditorFields);$('content-input').addEventListener('input',()=>{$('content-count').textContent=String($('content-input').value.length)});$('user-search').addEventListener('input',renderAssignableUsers);$('users-grid').addEventListener('change',updateUserSummary);$('editor-form').addEventListener('submit',saveRecord);
    $('time-input').addEventListener('blur',()=>{$('time-input').value=normalizeTime($('time-input').value)});$('time-button').addEventListener('click',event=>{event.preventDefault();openClock()});
    document.addEventListener('pointerdown',event=>{if(state.clock&&!$('time-picker-host').contains(event.target)&&event.target!==$('time-button'))closeClock()});
    document.addEventListener('keydown',event=>{if(event.key==='Escape'&&state.clock){event.preventDefault();closeClock();return}if(!state.modal)return;if(event.key==='Escape'){event.preventDefault();state.modal==='editor'?closeEditor():closeDay();return}if(event.key!=='Tab')return;const root=state.modal==='editor'?$('editor-modal'):$('day-modal');const focus=[...root.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')].filter(el=>!el.hidden&&el.offsetParent!==null);if(!focus.length)return;const first=focus[0],last=focus[focus.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}},true);
  }
  function openModal(id,kind,focusId){state.previousFocus=document.activeElement;state.modal=kind;$(id).classList.add('open');$(id).setAttribute('aria-hidden','false');document.body.classList.add('modal-open');requestAnimationFrame(()=>$(focusId)?.focus())}
  function closeModal(id){closeClock();$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true');state.modal=null;document.body.classList.remove('modal-open');setTimeout(()=>state.previousFocus?.focus?.(),10)}
  function closeEditor(){if(state.modal==='editor')closeModal('editor-modal')}
  function closeDay(){if(state.modal==='day')closeModal('day-modal')}

  function normalizeTime(value){const digits=String(value||'').replace(/\D/g,'').slice(0,4);if(!digits)return'';let hour,minute;if(digits.length<=2){hour=digits;minute='00'}else{hour=digits.slice(0,digits.length-2);minute=digits.slice(-2)}return String(Math.min(23,parseInt(hour,10)||0)).padStart(2,'0')+':'+String(Math.min(59,parseInt(minute,10)||0)).padStart(2,'0')}
  function svgElement(tag,attrs){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs||{}).forEach(([key,value])=>el.setAttribute(key,String(value)));return el}
  function closeClock(){if(!state.clock)return;$('time-picker-host').replaceChildren();state.clock=null}
  function openClock(){if(state.clock){closeClock();return}document.dispatchEvent(new CustomEvent('superapp:control-open',{detail:{trigger:$('time-button')}}));const current=normalizeTime($('time-input').value)||'12:00';let [hour,minute]=current.split(':').map(Number);let step=hour*2+(minute>=30?1:0);const panel=node('div','clock-picker-float');const readout=node('div','clock-readout');const svg=svgElement('svg',{class:'clock-face',viewBox:'0 0 228 228',role:'application','aria-label':'Relógio de 24 horas'});const center=114,radius=100;for(let i=0;i<48;i++){const angle=(i*7.5-90)*Math.PI/180,isHour=i%2===0,outer=radius-2,inner=outer-(isHour?12:7);svg.append(svgElement('line',{class:'clock-tick'+(isHour?' hour':''),x1:center+inner*Math.cos(angle),y1:center+inner*Math.sin(angle),x2:center+outer*Math.cos(angle),y2:center+outer*Math.sin(angle)}))}[0,6,12,18].forEach(value=>{const angle=(value*15-90)*Math.PI/180,r=76,text=svgElement('text',{class:'clock-num',x:center+r*Math.cos(angle),y:center+r*Math.sin(angle)});text.textContent=String(value).padStart(2,'0');svg.append(text)});const hand=svgElement('line',{class:'clock-hand',x1:center,y1:center,x2:center,y2:38}),tip=svgElement('circle',{class:'clock-hand-tip',cx:center,cy:38,r:4}),middle=svgElement('circle',{class:'clock-center',cx:center,cy:center,r:6});svg.append(hand,tip,middle);const actions=node('div','clock-actions'),cancel=node('button','btn','Cancelar'),save=node('button','btn primary','Definir');cancel.type=save.type='button';actions.append(cancel,save);panel.append(readout,svg,actions);$('time-picker-host').append(panel);state.clock={panel};function apply(next){step=((next%48)+48)%48;hour=Math.floor(step/2);minute=(step%2)*30;const angle=(step*7.5-90)*Math.PI/180,x=center+76*Math.cos(angle),y=center+76*Math.sin(angle);hand.setAttribute('x2',x);hand.setAttribute('y2',y);tip.setAttribute('cx',x);tip.setAttribute('cy',y);readout.textContent=String(hour).padStart(2,'0')+':'+String(minute).padStart(2,'0')}function select(event){const rect=svg.getBoundingClientRect(),x=(event.clientX-rect.left)*228/rect.width-center,y=(event.clientY-rect.top)*228/rect.height-center;let angle=Math.atan2(y,x)*180/Math.PI+90;if(angle<0)angle+=360;apply(Math.round(angle/7.5))}let dragging=false;svg.addEventListener('pointerdown',event=>{dragging=true;svg.setPointerCapture(event.pointerId);select(event)});svg.addEventListener('pointermove',event=>{if(dragging)select(event)});svg.addEventListener('pointerup',()=>{dragging=false});cancel.addEventListener('click',closeClock);save.addEventListener('click',()=>{$('time-input').value=String(hour).padStart(2,'0')+':'+String(minute).padStart(2,'0');closeClock();$('time-input').focus()});apply(step)}

  function meetingTypes(){const types=rows(state.capabilities.meeting_types);return types.length?types:['reuniao']}
  function fillMeetingTypes(selected){const select=$('type-input');select.replaceChildren();meetingTypes().forEach(type=>{const option=document.createElement('option');option.value=type;option.textContent=meta[type]?.label||type;select.append(option)});select.value=meetingTypes().includes(selected)?selected:meetingTypes()[0];select.dispatchEvent(new Event('change',{bubbles:true}));window.SuperAppUIControls?.refresh?.()}
  function syncEditorFields(){const mode=$('editor-mode').value,type=mode==='notice'?'aviso':$('type-input').value,isMeeting=mode==='meeting';$('type-field').hidden=!isMeeting;$('status-field').hidden=!isMeeting;$('date-field').hidden=!isMeeting;$('role-audience').hidden=!(mode==='notice'||type==='treinamento');$('user-audience').hidden=!(isMeeting&&type==='reuniao');$('date-input').required=isMeeting;$('time-input').required=isMeeting}
  function fillAudience(selected){const selectedSet=new Set(rows(selected));const wrap=$('audience-grid');wrap.replaceChildren();state.roles.forEach(role=>{const label=node('label','selection-option');const input=document.createElement('input');input.type='checkbox';input.value=role.code;input.checked=selectedSet.has(role.code);label.append(input,node('span','',role.display_name+' · '+role.code));wrap.append(label)})}
  function selectedUserIds(){return [...$('users-grid').querySelectorAll('input:checked')].map(input=>input.value)}
  function renderAssignableUsers(){const query=$('user-search').value.trim().toLocaleLowerCase('pt-BR'),selected=new Set(selectedUserIds()),wrap=$('users-grid');wrap.replaceChildren();const visible=state.users.filter(user=>[user.display_name,user.login_identifier,user.role_name,user.role_code,user.franchise_name].filter(Boolean).join(' ').toLocaleLowerCase('pt-BR').includes(query));if(!visible.length){wrap.append(node('p','empty-users','Nenhum usuário disponível para este filtro.'));return}visible.forEach(user=>{const label=node('label','selection-option'),input=document.createElement('input');input.type='checkbox';input.value=user.user_id;input.checked=selected.has(user.user_id);const copy=node('span');copy.append(node('strong','',user.display_name),node('small','',(user.role_name||user.role_code)+(user.franchise_name?' · '+user.franchise_name:'')));label.append(input,copy);wrap.append(label)})}
  function setSelectedUsers(ids){$('user-search').value='';renderAssignableUsers();const selected=new Set(rows(ids));$('users-grid').querySelectorAll('input').forEach(input=>{input.checked=selected.has(input.value)});updateUserSummary()}
  function updateUserSummary(){const count=selectedUserIds().length;$('users-summary').textContent=count?count+' participante'+(count===1?' selecionado.':'s selecionados.'):'Nenhum participante selecionado.'}
  function setDateInput(value){$('date-input').value=value||'';$('date-input').dispatchEvent(new Event('change',{bubbles:true}));window.SuperAppUIControls?.refresh?.()}
  function openEditor(item,forcedMode,postpone=false){const mode=forcedMode||(item?.type==='aviso'?'notice':'meeting');if(!item&&mode==='notice'&&!state.capabilities.create_notice)return;if(!item&&mode==='meeting'&&!state.capabilities.create_meeting)return;if(item&&!item.can_update)return;$('editor-form').reset();$('form-error').hidden=true;$('record-id').value=item?.id||'';$('record-version').value=item?.version||'';$('editor-mode').value=mode;const label=mode==='notice'?'aviso':'reunião';$('editor-title').textContent=postpone?'Adiar reunião':item?'Editar '+label:'Novo '+label;$('save-btn').textContent=postpone?'Salvar nova data':item?'Salvar alterações':'Salvar';$('title-input').value=item?.title||'';fillMeetingTypes(item?.type);$('status-input').value=postpone?'agendada':item?.status||'agendada';const parts=localParts(item?.event_date);setDateInput(parts.date);$('time-input').value=parts.time;$('content-input').value=item?.content||'';$('content-count').textContent=String($('content-input').value.length);$('link-input').value=item?.link||'';fillAudience(item?.audience_roles);setSelectedUsers(item?.assigned_user_ids);syncEditorFields();openModal('editor-modal','editor',postpone?'date-input':'title-input');if(postpone)requestAnimationFrame(()=>$('date-input').__uiControl?.button?.focus())}
  function formRecord(){const mode=$('editor-mode').value,type=mode==='notice'?'aviso':$('type-input').value,rawLink=$('link-input').value.trim(),date=$('date-input').value,time=normalizeTime($('time-input').value);return{title:$('title-input').value.trim(),type,status:mode==='notice'?null:$('status-input').value,content:$('content-input').value.trim(),event_date:mode==='meeting'&&date&&time?new Date(date+'T'+time+':00').toISOString():null,link:rawLink||null,audience_roles:(mode==='notice'||type==='treinamento')?[...$('audience-grid').querySelectorAll('input:checked')].map(input=>input.value):[],assigned_user_ids:type==='reuniao'?selectedUserIds():[]}}
  function validateRecord(record){if(!record.title)return'Informe o título.';if(!['aviso','reuniao','treinamento'].includes(record.type))return'Selecione um tipo válido.';if(!record.content)return'Informe a descrição.';if(record.type!=='aviso'&&!record.event_date)return'Informe data e hora válidas.';if(record.type==='reuniao'&&!record.assigned_user_ids.length)return'Selecione ao menos um participante.';if(record.link&&!safeHttpUrl(record.link))return'Informe um link HTTP ou HTTPS válido.';return''}
  async function saveRecord(event){event.preventDefault();const record=formRecord(),validation=validateRecord(record);if(validation){$('form-error').textContent=validation;$('form-error').hidden=false;return}const button=$('save-btn');button.disabled=true;button.textContent='Salvando…';try{const id=$('record-id').value;if(id)await rpc('comunicacao_update',{p_id:id,p_version:Number($('record-version').value),p_record:record});else await rpc('comunicacao_create',{p_record:record});closeEditor();toast(id?'Publicação atualizada.':'Publicação criada.');await loadItems()}catch(error){$('form-error').textContent=safeMessage(error,'Não foi possível salvar a publicação.');$('form-error').hidden=false}finally{button.disabled=false;button.textContent=$('record-id').value?'Salvar alterações':'Salvar'}}
  function recordFromItem(item,status){return{title:item.title,type:item.type,status,content:item.content,event_date:item.event_date,link:item.link||null,audience_roles:rows(item.audience_roles),assigned_user_ids:rows(item.assigned_user_ids)}}
  async function changeStatus(item,status){if(!item.can_update)return;try{await rpc('comunicacao_update',{p_id:item.id,p_version:Number(item.version),p_record:recordFromItem(item,status)});toast('Reunião marcada como '+statusLabels[status].toLowerCase()+'.');await loadItems()}catch(error){toast(safeMessage(error,'Não foi possível atualizar a reunião.'),'error')}}
  async function deleteRecord(item){if(!item.can_delete)return;const confirmed=await window.SuperAppConfirm.delete('“'+item.title+'” será removido permanentemente.',{title:'Excluir publicação?',confirmLabel:'Excluir'});if(!confirmed)return;try{await rpc('comunicacao_delete',{p_id:item.id,p_version:Number(item.version)});toast('Publicação excluída.');await loadItems()}catch(error){toast(safeMessage(error,'Não foi possível excluir a publicação.'),'error')}}

  function emptyState(title,message,compact=false){const wrap=node('div','empty-state'+(compact?' compact':'')),content=node('div');content.append(node('div','empty-icon','◇'),node('h3','',title),node('p','',message));wrap.append(content);return wrap}
  function cardFor(item){const itemMeta=meta[item.type]||meta.aviso,card=node('article','communication-card type-'+item.type);card.id='communication-'+item.id;const icon=node('div','type-icon',itemMeta.icon);icon.setAttribute('aria-hidden','true');const main=node('div','card-main'),topline=node('div','card-topline');topline.append(node('span','type-badge',itemMeta.label),node('span','audience-badge',audienceLabel(item)));if(item.type!=='aviso')topline.append(node('span','status-badge '+(item.status||'agendada'),statusLabels[item.status]||'Agendada'));main.append(topline,node('h3','',item.title),node('p','card-content',item.content));const details=node('div','card-meta');details.append(node('span','',item.event_date?'Data: '+formatDate(item.event_date):'Publicado em '+formatCreated(item.created_at)),node('span','',item.created_by_name?'Por '+item.created_by_name:'Comunicação 321 Modular'));if(rows(item.assigned_user_names).length)details.append(node('span','','Participantes: '+rows(item.assigned_user_names).join(', ')));const url=safeHttpUrl(item.link);if(url){const link=node('a','','Abrir link ↗');link.href=url;link.target='_blank';link.rel='noopener noreferrer';details.append(link)}main.append(details);if(item.type!=='aviso'&&item.can_update){const statusActions=node('div','status-actions');if(item.status!=='concluida'){const complete=node('button','mini-btn complete','Concluir');complete.type='button';complete.addEventListener('click',()=>changeStatus(item,'concluida'));statusActions.append(complete)}if(item.status!=='cancelada'){const cancel=node('button','mini-btn cancel','Cancelar reunião');cancel.type='button';cancel.addEventListener('click',()=>changeStatus(item,'cancelada'));statusActions.append(cancel)}const postpone=node('button','mini-btn','Adiar');postpone.type='button';postpone.addEventListener('click',()=>openEditor(item,null,true));statusActions.append(postpone);main.append(statusActions)}const actions=node('div','card-actions');if(item.can_update){const edit=node('button','icon-btn','✎');edit.type='button';edit.title='Editar';edit.setAttribute('aria-label','Editar '+item.title);edit.addEventListener('click',()=>openEditor(item));actions.append(edit)}if(item.can_delete){const remove=node('button','icon-btn delete','×');remove.type='button';remove.title='Excluir';remove.setAttribute('aria-label','Excluir '+item.title);remove.addEventListener('click',()=>deleteRecord(item));actions.append(remove)}card.append(icon,main,actions);return card}
  function listPanel(items,title,emptyMessage){const section=node('section','feed-main'),heading=node('div','section-heading'),copy=node('div');copy.append(node('span','eyebrow',state.view==='notices'?'Mural interno':'Agenda interna'),node('h2','',title));heading.append(copy,node('span','result-count',items.length+' '+(items.length===1?'registro':'registros')));const feed=node('div','feed');if(state.loading){for(let i=0;i<4;i++)feed.append(node('div','skeleton'))}else if(!items.length)feed.append(emptyState('Nenhum registro encontrado',emptyMessage));else items.forEach(item=>feed.append(cardFor(item)));section.append(heading,feed);return section}
  function meetingItems(){return state.items.filter(item=>item.type!=='aviso')}
  function scheduledItems(){return meetingItems().filter(item=>dateValue(item.event_date))}
  function calendarBlock(large=false){const section=node('section',large?'calendar-page':'panel'),head=node('div','calendar-head'),prev=node('button','icon-btn','‹'),next=node('button','icon-btn','›'),title=node('h2');prev.type=next.type='button';prev.setAttribute('aria-label','Mês anterior');next.setAttribute('aria-label','Próximo mês');prev.addEventListener('click',()=>{state.calendar=new Date(state.calendar.getFullYear(),state.calendar.getMonth()-1,1);renderView()});next.addEventListener('click',()=>{state.calendar=new Date(state.calendar.getFullYear(),state.calendar.getMonth()+1,1);renderView()});const base=new Date(state.calendar.getFullYear(),state.calendar.getMonth(),1);title.textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(base).replace(/^./,char=>char.toUpperCase());head.append(prev,title,next);const weekdays=node('div','calendar-weekdays');'DSTQQSS'.split('').forEach(day=>weekdays.append(node('span','',day)));const grid=node('div','calendar-grid'),first=new Date(base);first.setDate(1-base.getDay());const today=new Date(),events=scheduledItems();for(let index=0;index<42;index++){const day=new Date(first);day.setDate(first.getDate()+index);const button=node('button','calendar-day',day.getDate());button.type='button';if(day.getMonth()!==base.getMonth())button.classList.add('outside');if(sameDay(day,today))button.classList.add('today');const dayEvents=events.filter(item=>sameDay(dateValue(item.event_date),day));if(dayEvents.length){button.classList.add('has-events');const dots=node('span','day-dots');[...new Set(dayEvents.map(item=>item.type))].forEach(type=>dots.append(node('i','dot '+type)));button.append(dots);if(large)button.append(node('span','day-count',dayEvents.length+' reunião'+(dayEvents.length===1?'':'ões')))}button.setAttribute('aria-label',formatDate(day,false)+(dayEvents.length?' · '+dayEvents.length+' reuniões':''));button.addEventListener('click',()=>openDay(day,dayEvents));grid.append(button)}const legend=node('div','calendar-legend'),a=node('span'),b=node('span');a.append(node('i','dot reuniao'),document.createTextNode('Reuniões'));b.append(node('i','dot treinamento'),document.createTextNode('Treinamentos'));legend.append(a,b);section.append(head,weekdays,grid,legend);return section}
  function openDay(date,items){$('day-title').textContent=new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(date).replace(/^./,char=>char.toUpperCase());const list=$('day-list');list.replaceChildren();if(!items.length)list.append(emptyState('Nenhuma reunião','Não há reuniões ou treinamentos agendados para este dia.',true));else items.sort((a,b)=>dateValue(a.event_date)-dateValue(b.event_date)).forEach(item=>{const article=node('article','day-event');article.append(node('span','eyebrow',meta[item.type]?.label||'Reunião'),node('h3','',item.title),node('p','',item.content));const details=node('div','day-event-meta');details.append(node('span','',formatDate(item.event_date)),node('span','',statusLabels[item.status]||'Agendada'),node('span','',audienceLabel(item)));if(rows(item.assigned_user_names).length)details.append(node('span','','Participantes: '+rows(item.assigned_user_names).join(', ')));article.append(details);list.append(article)});openModal('day-modal','day','day-close')}
  function renderView(){const root=$('view-root');root.replaceChildren();root.classList.remove('view-enter');void root.offsetWidth;root.classList.add('view-enter');if(state.view==='calendar'){root.append(calendarBlock(true));return}if(state.view==='notices'){root.append(listPanel(state.items.filter(item=>item.type==='aviso'),'Avisos publicados','Os novos avisos aparecerão aqui.'));return}const all=meetingItems(),visible=state.pendingOnly?all.filter(item=>item.status==='agendada'):all,toolbar=node('div','meeting-toolbar'),toggle=node('label','pending-toggle'),input=document.createElement('input');input.type='checkbox';input.checked=state.pendingOnly;input.addEventListener('change',()=>{state.pendingOnly=input.checked;renderView()});toggle.append(input,node('span','','Somente reuniões não concluídas'));toolbar.append(toggle,node('span','result-count',all.length+' reunião'+(all.length===1?'':'ões')));root.append(toolbar,listPanel(visible,'Reuniões e treinamentos','Nenhuma reunião corresponde ao filtro selecionado.'))}
  async function loadItems(){state.loading=true;renderView();$('refresh-btn').disabled=true;try{state.items=rows(await rpc('comunicacao_list')).sort((a,b)=>dateValue(b.created_at)-dateValue(a.created_at));state.loading=false;renderView()}catch(error){state.loading=false;state.items=[];renderView();$('view-root').replaceChildren(emptyState('Não foi possível carregar',safeMessage(error,'Atualize a página e tente novamente.')));toast(safeMessage(error,'Não foi possível carregar as publicações.'),'error')}finally{$('refresh-btn').disabled=false}}
  async function boot(event){try{state.client=window.SuperAppAuth.getScopedClient('core');state.profile=await window.SuperAppAuth.getProfile();const [caps,rolesList]=await Promise.all([rpc('comunicacao_capabilities'),rpc('comunicacao_roles')]);state.capabilities={...state.capabilities,...(caps||{})};state.roles=rows(rolesList);if(['ADM','GEng','GInd','GFrq'].includes(state.capabilities.role_code)){try{state.users=rows(await rpc('comunicacao_assignable_users'))}catch(error){console.error('[comunicacao] participantes',error)}}$('side-user-name').textContent=state.profile?.display_name||event?.detail?.session?.user?.email||'Usuário';$('side-user-role').textContent=(state.profile?.role_name||state.profile?.role_code||'Acesso operacional')+' · '+roleScope(state.profile);setupShell();setupModals();state.calendar=new Date(new Date().getFullYear(),new Date().getMonth(),1);$('app-shell').classList.add('active');$('app-shell').setAttribute('aria-busy','false');setView('notices');await loadItems()}catch(error){toast(safeMessage(error,'Não foi possível iniciar o Painel de Comunicação.'),'error')}finally{window.SuperAppAuth?.releaseAppGuard?.()}}
  window.addEventListener('superapp:authorized',boot,{once:true});
})();
