(function bootCommunicationApp(){
  'use strict';
  const $=id=>document.getElementById(id);
  const state={client:null,profile:null,capabilities:{view:false,create_content:false,create_event:false,update:false,delete:false},roles:[],users:[],items:[],filter:'todos',view:'feed',calendar:new Date(),loading:true,modal:null,previousFocus:null};
  const meta={aviso:{label:'Aviso',icon:'!'},treinamento:{label:'Treinamento',icon:'T'},evento:{label:'Evento',icon:'E'},reuniao:{label:'Evento',icon:'E'}};
  const eventTypes=new Set(['evento','reuniao','treinamento']);

  function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=String(text);return el}
  function rows(value){if(Array.isArray(value))return value;if(Array.isArray(value?.items))return value.items;return value?[value]:[]}
  function safeMessage(error,fallback){console.error('[comunicacao]',error);return window.SuperAppAuth?.getSafeAuthMessage?.(error,fallback)||fallback}
  async function rpc(name,params){const {data,error}=await state.client.rpc(name,params||{});if(error)throw error;return data}
  function toast(message,type){const el=$('toast');el.textContent=message;el.className='toast show'+(type?' '+type:'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>{el.className='toast'},3400)}
  function dateValue(value){const date=value?new Date(value):null;return date&&!Number.isNaN(date.getTime())?date:null}
  function sameDay(a,b){return a&&b&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
  function formatDate(value,withTime=true){const date=dateValue(value);if(!date)return 'Data não informada';return new Intl.DateTimeFormat('pt-BR',withTime?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'long'}).format(date)}
  function formatCreated(value){const date=dateValue(value);return date?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(date):''}
  function safeHttpUrl(value){if(!value)return null;try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:null}catch(_){return null}}
  function roleScope(profile){if(profile?.franchise_name)return 'Franquia · '+profile.franchise_name;if(profile?.unit_name)return 'Matriz · '+profile.unit_name;return 'Matriz · acesso global'}
  function localDateTime(value){const date=dateValue(value);if(!date)return '';const shifted=new Date(date.getTime()-date.getTimezoneOffset()*60000);return shifted.toISOString().slice(0,16)}
  function audienceLabel(item){if(item.type==='evento'||item.type==='reuniao'){const names=rows(item.assigned_user_names);return names.length?names.length+' participante'+(names.length===1?'':'s'):'Evento geral'}const codes=rows(item.audience_roles);return codes.length?codes.map(code=>state.roles.find(role=>role.code===code)?.display_name||code).join(', '):'Todos os cargos'}

  function applyTheme(theme,persist=true){const normalized=theme==='dark'?'dark':'light';document.documentElement.dataset.theme=normalized;const toggle=$('theme-toggle'),knob=toggle?.querySelector('.knob');if(knob)knob.textContent=normalized==='dark'?'🌙':'☀️';if(toggle){toggle.setAttribute('aria-pressed',String(normalized==='dark'));toggle.setAttribute('aria-label',normalized==='dark'?'Ativar modo claro':'Ativar modo escuro')}if(persist){try{localStorage.setItem('321modular_theme',normalized)}catch(_){}}}
  function closeMenu(){$('aside')?.classList.remove('aside-open');$('aside-backdrop')?.classList.remove('active');$('menu-btn')?.setAttribute('aria-expanded','false')}
  function setupShell(){
    $('menu-btn').addEventListener('click',()=>{const open=$('aside').classList.toggle('aside-open');$('aside-backdrop').classList.toggle('active',open);$('menu-btn').setAttribute('aria-expanded',String(open))});
    $('aside-backdrop').addEventListener('click',closeMenu);$('theme-toggle').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
    $('logout-btn').addEventListener('click',()=>{location.href=window.SuperAppAuth.getPortalUrl()});$('refresh-btn').addEventListener('click',loadItems);
    $('new-content-btn').addEventListener('click',()=>openEditor(null,'content'));$('new-event-btn').addEventListener('click',()=>openEditor(null,'event'));
    document.querySelectorAll('#nav-tabs [data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
    window.addEventListener('resize',()=>{if(innerWidth>880)closeMenu()});window.addEventListener('storage',event=>{if(event.key==='321modular_theme')applyTheme(event.newValue||'light',false)});applyTheme(document.documentElement.dataset.theme||'light',false);
  }
  function setView(view){state.view=view==='calendar'?'calendar':'feed';document.querySelectorAll('#nav-tabs [data-view]').forEach(button=>{const active=button.dataset.view===state.view;button.classList.toggle('active',active);button.toggleAttribute('aria-current',active)});$('view-title').textContent=state.view==='calendar'?'Calendário':'Painel de Comunicação';$('view-subtitle').textContent=state.view==='calendar'?'Consulte os eventos e treinamentos em cada dia.':'Avisos, eventos e treinamentos em um só lugar.';closeMenu();renderView()}

  function setupModals(){
    $('editor-close').addEventListener('click',closeEditor);$('cancel-btn').addEventListener('click',closeEditor);$('editor-modal').addEventListener('mousedown',event=>{if(event.target===$('editor-modal'))closeEditor()});
    $('day-close').addEventListener('click',closeDay);$('day-done').addEventListener('click',closeDay);$('day-modal').addEventListener('mousedown',event=>{if(event.target===$('day-modal'))closeDay()});
    $('type-input').addEventListener('change',syncEditorFields);$('content-input').addEventListener('input',()=>{$('content-count').textContent=String($('content-input').value.length)});$('user-search').addEventListener('input',renderAssignableUsers);$('users-grid').addEventListener('change',updateUserSummary);$('editor-form').addEventListener('submit',saveRecord);
    document.addEventListener('keydown',event=>{if(!state.modal)return;if(event.key==='Escape'){event.preventDefault();state.modal==='editor'?closeEditor():closeDay();return}if(event.key!=='Tab')return;const root=state.modal==='editor'?$('editor-modal'):$('day-modal');const focus=[...root.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')].filter(el=>!el.hidden&&el.offsetParent!==null);if(!focus.length)return;const first=focus[0],last=focus[focus.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}},true);
  }
  function openModal(id,kind,focusId){state.previousFocus=document.activeElement;state.modal=kind;$(id).classList.add('open');$(id).setAttribute('aria-hidden','false');document.body.classList.add('modal-open');requestAnimationFrame(()=>$(focusId)?.focus())}
  function closeModal(id){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true');state.modal=null;document.body.classList.remove('modal-open');setTimeout(()=>state.previousFocus?.focus?.(),10)}
  function closeEditor(){if(state.modal==='editor')closeModal('editor-modal')}
  function closeDay(){if(state.modal==='day')closeModal('day-modal')}
  function syncEditorFields(){const mode=$('editor-mode').value;const type=mode==='event'?'evento':$('type-input').value;$('type-field').hidden=mode==='event';$('role-audience').hidden=mode==='event';$('user-audience').hidden=mode!=='event';$('date-field').hidden=type==='aviso';$('date-input').required=type!=='aviso';if(type==='aviso')$('date-input').value=''}
  function fillAudience(selected){const selectedSet=new Set(rows(selected));const wrap=$('audience-grid');wrap.replaceChildren();state.roles.forEach(role=>{const label=node('label','selection-option');const input=document.createElement('input');input.type='checkbox';input.value=role.code;input.checked=selectedSet.has(role.code);label.append(input,node('span','',role.display_name+' · '+role.code));wrap.append(label)})}
  function selectedUserIds(){return [...$('users-grid').querySelectorAll('input:checked')].map(input=>input.value)}
  function renderAssignableUsers(){const query=$('user-search').value.trim().toLocaleLowerCase('pt-BR');const selected=new Set(selectedUserIds());const wrap=$('users-grid');wrap.replaceChildren();const visible=state.users.filter(user=>[user.display_name,user.login_identifier,user.role_name,user.role_code,user.franchise_name].filter(Boolean).join(' ').toLocaleLowerCase('pt-BR').includes(query));if(!visible.length){wrap.append(node('p','empty-users','Nenhum usuário disponível para este filtro.'));return}visible.forEach(user=>{const label=node('label','selection-option');const input=document.createElement('input');input.type='checkbox';input.value=user.user_id;input.checked=selected.has(user.user_id);const copy=node('span');copy.append(node('strong','',user.display_name),node('small','',(user.role_name||user.role_code)+(user.franchise_name?' · '+user.franchise_name:'')));label.append(input,copy);wrap.append(label)})}
  function setSelectedUsers(ids){$('user-search').value='';renderAssignableUsers();const selected=new Set(rows(ids));$('users-grid').querySelectorAll('input').forEach(input=>{input.checked=selected.has(input.value)});updateUserSummary()}
  function updateUserSummary(){const count=selectedUserIds().length;$('users-summary').textContent=count?count+' participante'+(count===1?' selecionado.':'s selecionados.'):'Nenhum participante selecionado.'}
  function openEditor(item,forcedMode){const mode=forcedMode||(item&&['evento','reuniao'].includes(item.type)?'event':'content');if(!item&&mode==='event'&&!state.capabilities.create_event)return;if(!item&&mode==='content'&&!state.capabilities.create_content)return;if(item&&!item.can_update)return;
    $('editor-form').reset();$('form-error').hidden=true;$('record-id').value=item?.id||'';$('record-version').value=item?.version||'';$('editor-mode').value=mode;$('editor-title').textContent=item?(mode==='event'?'Editar evento':'Editar publicação'):(mode==='event'?'Novo evento':'Novo aviso ou treinamento');$('save-btn').textContent=item?'Salvar alterações':'Salvar';$('title-input').value=item?.title||'';$('type-input').value=item?.type==='treinamento'?'treinamento':'aviso';$('date-input').value=localDateTime(item?.event_date);$('content-input').value=item?.content||'';$('content-count').textContent=String($('content-input').value.length);$('link-input').value=item?.link||'';fillAudience(item?.audience_roles);setSelectedUsers(item?.assigned_user_ids);syncEditorFields();openModal('editor-modal','editor','title-input')}
  function formRecord(){const mode=$('editor-mode').value;const type=mode==='event'?'evento':$('type-input').value;const rawLink=$('link-input').value.trim();const eventDate=type==='aviso'?null:$('date-input').value;return{title:$('title-input').value.trim(),type,content:$('content-input').value.trim(),event_date:eventDate?new Date(eventDate).toISOString():null,link:rawLink||null,audience_roles:mode==='content'?[...$('audience-grid').querySelectorAll('input:checked')].map(input=>input.value):[],assigned_user_ids:mode==='event'?selectedUserIds():[]}}
  function validateRecord(record){if(!record.title)return 'Informe o título.';if(!['aviso','treinamento','evento'].includes(record.type))return 'Selecione um tipo válido.';if(!record.content)return 'Informe a descrição.';if(record.type!=='aviso'&&!record.event_date)return 'Informe a data e a hora.';if(record.type==='evento'&&!record.assigned_user_ids.length)return 'Selecione ao menos um participante.';if(record.link&&!safeHttpUrl(record.link))return 'Informe um link HTTP ou HTTPS válido.';return ''}
  async function saveRecord(event){event.preventDefault();const record=formRecord();const validation=validateRecord(record);if(validation){$('form-error').textContent=validation;$('form-error').hidden=false;return}const button=$('save-btn');button.disabled=true;button.textContent='Salvando…';try{const id=$('record-id').value;if(id)await rpc('comunicacao_update',{p_id:id,p_version:Number($('record-version').value),p_record:record});else await rpc('comunicacao_create',{p_record:record});closeEditor();toast(id?'Publicação atualizada.':'Publicação criada.');await loadItems()}catch(error){$('form-error').textContent=safeMessage(error,'Não foi possível salvar a publicação.');$('form-error').hidden=false}finally{button.disabled=false;button.textContent=$('record-id').value?'Salvar alterações':'Salvar'}}
  async function deleteRecord(item){if(!item.can_delete)return;const confirmed=await window.SuperAppConfirm.delete('“'+item.title+'” será removido permanentemente.',{title:'Excluir publicação?',confirmLabel:'Excluir'});if(!confirmed)return;try{await rpc('comunicacao_delete',{p_id:item.id,p_version:Number(item.version)});toast('Publicação excluída.');await loadItems()}catch(error){toast(safeMessage(error,'Não foi possível excluir a publicação.'),'error')}}

  function setFilter(filter){state.filter=filter;renderView()}
  function countFor(filter){if(filter==='todos')return state.items.length;if(filter==='evento')return state.items.filter(item=>item.type==='evento'||item.type==='reuniao').length;return state.items.filter(item=>item.type===filter).length}
  function filterBar(){const bar=node('div','filters');[['todos','Todos'],['aviso','Avisos'],['evento','Eventos'],['treinamento','Treinamentos']].forEach(([key,labelText])=>{const button=node('button','filter-chip'+(state.filter===key?' active':''));button.type='button';button.dataset.filter=key;button.setAttribute('aria-pressed',String(state.filter===key));button.append(document.createTextNode(labelText+' '),node('span','',countFor(key)));button.addEventListener('click',()=>setFilter(key));bar.append(button)});return bar}
  function emptyState(title,message,compact=false){const wrap=node('div','empty-state'+(compact?' compact':''));const content=node('div');content.append(node('div','empty-icon','◇'),node('h3','',title),node('p','',message));wrap.append(content);return wrap}
  function cardFor(item){const itemMeta=meta[item.type]||meta.aviso;const card=node('article','communication-card type-'+item.type);card.id='communication-'+item.id;const icon=node('div','type-icon',itemMeta.icon);icon.setAttribute('aria-hidden','true');const main=node('div','card-main');const topline=node('div','card-topline');topline.append(node('span','type-badge',itemMeta.label),node('span','audience-badge',audienceLabel(item)));main.append(topline,node('h3','',item.title),node('p','card-content',item.content));const details=node('div','card-meta');details.append(node('span','',item.event_date?'Data: '+formatDate(item.event_date):'Publicado em '+formatCreated(item.created_at)),node('span','',item.created_by_name?'Por '+item.created_by_name:'Comunicação 321 Modular'));if(rows(item.assigned_user_names).length)details.append(node('span','','Participantes: '+rows(item.assigned_user_names).join(', ')));const url=safeHttpUrl(item.link);if(url){const link=node('a','','Abrir link ↗');link.href=url;link.target='_blank';link.rel='noopener noreferrer';details.append(link)}main.append(details);const actions=node('div','card-actions');if(item.can_update){const edit=node('button','icon-btn','✎');edit.type='button';edit.title='Editar';edit.setAttribute('aria-label','Editar '+item.title);edit.addEventListener('click',()=>openEditor(item));actions.append(edit)}if(item.can_delete){const remove=node('button','icon-btn delete','×');remove.type='button';remove.title='Excluir';remove.setAttribute('aria-label','Excluir '+item.title);remove.addEventListener('click',()=>deleteRecord(item));actions.append(remove)}card.append(icon,main,actions);return card}
  function visibleItems(){if(state.filter==='todos')return state.items;if(state.filter==='evento')return state.items.filter(item=>item.type==='evento'||item.type==='reuniao');return state.items.filter(item=>item.type===state.filter)}
  function feedPanel(){const section=node('section','feed-main');const heading=node('div','section-heading');const copy=node('div');copy.append(node('span','eyebrow','Mural interno'),node('h2','','Últimas publicações'));heading.append(copy,node('span','result-count',visibleItems().length+' '+(visibleItems().length===1?'registro':'registros')));const feed=node('div','feed');if(state.loading){for(let i=0;i<4;i++)feed.append(node('div','skeleton'))}else if(!visibleItems().length)feed.append(emptyState('Nenhuma publicação encontrada',state.items.length?'Não há publicações para este filtro.':'As novas publicações aparecerão aqui.'));else visibleItems().forEach(item=>feed.append(cardFor(item)));section.append(heading,feed);return section}
  function scheduledItems(){return state.items.filter(item=>eventTypes.has(item.type)&&dateValue(item.event_date))}
  function calendarBlock(large=false){const section=node('section',large?'calendar-page':'panel');const head=node('div','calendar-head');const prev=node('button','icon-btn','‹'),next=node('button','icon-btn','›'),title=node('h2');prev.type=next.type='button';prev.setAttribute('aria-label','Mês anterior');next.setAttribute('aria-label','Próximo mês');prev.addEventListener('click',()=>{state.calendar=new Date(state.calendar.getFullYear(),state.calendar.getMonth()-1,1);renderView()});next.addEventListener('click',()=>{state.calendar=new Date(state.calendar.getFullYear(),state.calendar.getMonth()+1,1);renderView()});const base=new Date(state.calendar.getFullYear(),state.calendar.getMonth(),1);title.textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(base).replace(/^./,char=>char.toUpperCase());head.append(prev,title,next);const weekdays=node('div','calendar-weekdays');'DSTQQSS'.split('').forEach(day=>weekdays.append(node('span','',day)));const grid=node('div','calendar-grid');const first=new Date(base);first.setDate(1-base.getDay());const today=new Date(),events=scheduledItems();for(let index=0;index<42;index++){const day=new Date(first);day.setDate(first.getDate()+index);const button=node('button','calendar-day',day.getDate());button.type='button';if(day.getMonth()!==base.getMonth())button.classList.add('outside');if(sameDay(day,today))button.classList.add('today');const dayEvents=events.filter(item=>sameDay(dateValue(item.event_date),day));if(dayEvents.length){button.classList.add('has-events');const dots=node('span','day-dots');[...new Set(dayEvents.map(item=>item.type))].forEach(type=>dots.append(node('i','dot '+type)));button.append(dots);if(large)button.append(node('span','day-count',dayEvents.length+' evento'+(dayEvents.length===1?'':'s')))}button.setAttribute('aria-label',formatDate(day,false)+(dayEvents.length?' · '+dayEvents.length+' eventos':''));button.addEventListener('click',()=>openDay(day,dayEvents));grid.append(button)}const legend=node('div','calendar-legend');const a=node('span'),b=node('span');a.append(node('i','dot evento'),document.createTextNode('Eventos'));b.append(node('i','dot treinamento'),document.createTextNode('Treinamentos'));legend.append(a,b);section.append(head,weekdays,grid,legend);return section}
  function upcomingPanel(){const section=node('section','panel');const heading=node('div','section-heading');const copy=node('div');copy.append(node('span','eyebrow','Agenda'),node('h2','','Próximos eventos'));heading.append(copy);const wrap=node('div','upcoming-list');const upcoming=scheduledItems().filter(item=>dateValue(item.event_date)>=new Date()).sort((a,b)=>dateValue(a.event_date)-dateValue(b.event_date)).slice(0,5);if(!upcoming.length)wrap.append(emptyState('Agenda livre','Nenhum evento futuro agendado.',true));else upcoming.forEach(item=>{const date=dateValue(item.event_date),button=node('button','upcoming-item');button.type='button';const dateBox=node('span','event-date');dateBox.append(node('strong','',String(date.getDate()).padStart(2,'0')),node('small','',new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(date).replace('.','')));const text=node('span','upcoming-copy');text.append(node('strong','',item.title),node('small','',new Intl.DateTimeFormat('pt-BR',{weekday:'short',hour:'2-digit',minute:'2-digit'}).format(date)));button.append(dateBox,text);button.addEventListener('click',()=>openDay(date,scheduledItems().filter(other=>sameDay(dateValue(other.event_date),date))));wrap.append(button)});section.append(heading,wrap);return section}
  function openDay(date,items){$('day-title').textContent=new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(date).replace(/^./,char=>char.toUpperCase());const list=$('day-list');list.replaceChildren();if(!items.length)list.append(emptyState('Nenhum evento','Não há eventos ou treinamentos agendados para este dia.',true));else items.sort((a,b)=>dateValue(a.event_date)-dateValue(b.event_date)).forEach(item=>{const article=node('article','day-event');article.append(node('span','eyebrow',meta[item.type]?.label||'Evento'),node('h3','',item.title),node('p','',item.content));const details=node('div','day-event-meta');details.append(node('span','',formatDate(item.event_date)),node('span','',audienceLabel(item)));if(rows(item.assigned_user_names).length)details.append(node('span','','Participantes: '+rows(item.assigned_user_names).join(', ')));const url=safeHttpUrl(item.link);if(url){const link=node('a','','Abrir link ↗');link.href=url;link.target='_blank';link.rel='noopener noreferrer';details.append(link)}article.append(details);list.append(article)});openModal('day-modal','day','day-close')}
  function renderView(){const root=$('view-root');root.replaceChildren();root.classList.remove('view-enter');void root.offsetWidth;root.classList.add('view-enter');if(state.view==='calendar'){root.append(calendarBlock(true));return}root.append(filterBar());const layout=node('div','feed-layout'),side=node('aside','side-column');layout.append(feedPanel());side.append(calendarBlock(false),upcomingPanel());layout.append(side);root.append(layout)}

  async function loadItems(){state.loading=true;renderView();$('refresh-btn').disabled=true;try{state.items=rows(await rpc('comunicacao_list')).sort((a,b)=>dateValue(b.created_at)-dateValue(a.created_at));state.loading=false;renderView()}catch(error){state.loading=false;state.items=[];renderView();$('view-root').replaceChildren(emptyState('Não foi possível carregar',safeMessage(error,'Atualize a página e tente novamente.')));toast(safeMessage(error,'Não foi possível carregar as publicações.'),'error')}finally{$('refresh-btn').disabled=false}}
  async function boot(event){try{state.client=window.SuperAppAuth.getScopedClient('core');state.profile=await window.SuperAppAuth.getProfile();const [caps,rolesList]=await Promise.all([rpc('comunicacao_capabilities'),rpc('comunicacao_roles')]);state.capabilities={...state.capabilities,...(caps||{})};state.roles=rows(rolesList);if(state.capabilities.create_event){try{state.users=rows(await rpc('comunicacao_assignable_users'))}catch(error){console.error('[comunicacao] participantes',error);state.users=[]}}$('side-user-name').textContent=state.profile?.display_name||event?.detail?.session?.user?.email||'Usuário';$('side-user-role').textContent=(state.profile?.role_name||state.profile?.role_code||'Acesso operacional')+' · '+roleScope(state.profile);$('new-content-btn').hidden=!state.capabilities.create_content;$('new-event-btn').hidden=!state.capabilities.create_event;setupShell();setupModals();state.calendar=new Date(new Date().getFullYear(),new Date().getMonth(),1);$('app-shell').classList.add('active');$('app-shell').setAttribute('aria-busy','false');await loadItems()}catch(error){toast(safeMessage(error,'Não foi possível iniciar o Painel de Comunicação.'),'error')}finally{window.SuperAppAuth?.releaseAppGuard?.()}}
  window.addEventListener('superapp:authorized',boot,{once:true});
})();
