
    const catalog=[['gestao','Gestão','Engenharia e Indústria da Matriz','Matriz','IconGestaoEngenharia.svg'],['planta','Planta','Catálogo de plantas homologadas','Matriz e franquias','IconPlanta.svg'],['playbook','Playbook','Orientações da operação de franquias','Matriz e franquias','IconPlaybook.svg'],['checklist','Checklist','Montagem e conferência de obra','Matriz e franquias','IconChecklistObra.svg'],['financeiro','Gestão Financeira','Obras e saldos operacionais','Matriz','IconGestaoFinanceira.svg']];
    const $=id=>document.getElementById(id), config=window.SUPERAPP_CONFIG||{}, loginForm=$('login-form'),identifier=$('identifier'),password=$('password'),passwordToggle=$('password-toggle'),message=$('form-message'), button=$('login-button'), authView=$('auth-view'), appsSection=$('apps-section'), adminSection=$('admin-section'), appsPanel=$('apps-panel'), adminTab=$('admin-tab'), appsTab=$('apps-tab'), appsGrid=$('apps-grid'), rememberLogin=$('remember-login'), themeToggles=[...document.querySelectorAll('[data-theme-toggle]')];
    const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])), setMessage=(target,text,kind)=>{target.textContent=text||'';target.className='form-message '+(kind||'')}, appUrl=route=>route==='checklist'?'https://checklist.321modular.com.br/':new URL(String(config.appBasePath||'./')+route+'/',document.baseURI).href;
    let adminUsers=[],adminRoles=[],adminFranchises=[],adminUnits=[],adminAppPermissions=[],adminCurrentUserId='';
    const adminUsersTab=$('admin-users-tab'),adminAppsTab=$('admin-apps-tab'),adminUsersPanel=$('admin-users-panel'),adminAppsPanel=$('admin-apps-panel'),adminAppsMessage=$('admin-apps-message'),adminAppPermissionsHead=$('admin-app-permissions-head'),adminAppPermissionsBody=$('admin-app-permissions');
    function showProfile(profile){const name=profile?.display_name||'Usuário', role=profile?.role_name||profile?.role_code||'Acesso operacional', scope=profile?.franchise_name?'Franquia · '+profile.franchise_name:profile?.unit_name?'Matriz · '+profile.unit_name:'Matriz · acesso global';$('profile-name').textContent=name;$('profile-scope').textContent=scope;$('profile-initials').textContent=name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'3M';$('welcome-name').textContent=name.split(/\s+/)[0];$('welcome-role').textContent=role;$('welcome-scope').textContent=scope}
function renderApps(entitlements){const allowed=new Map(entitlements.map(app=>[app.app_code,app])),visible=catalog.filter(([code])=>allowed.has(code));$('apps-count').textContent=visible.length+' '+(visible.length===1?'liberado':'liberados');appsGrid.innerHTML=visible.length?visible.map(([code,name,description,scope,icon])=>'<a class="app-card" href="'+appUrl(code)+'"><span class="app-card-icon"><img src="shared/'+icon+'" alt=""></span><span class="app-card-content"><strong>'+escapeHtml(name)+'</strong><span>'+escapeHtml(description)+'</span></span><span class="app-card-footer"><small>'+escapeHtml(scope)+'</small><b aria-hidden="true">→</b></span></a>').join(''):'<p class="form-message error">Nenhum aplicativo autorizado para este usuário.</p>'}
    function showAuthenticated(profile,entitlements){showProfile(profile);renderApps(entitlements);authView.classList.add('hidden');$('login-theme-toggle')?.classList.add('hidden');appsSection.classList.remove('hidden');if(profile?.is_adm){adminTab.classList.remove('hidden');initAdmin()}}
    async function showSession(){if(!window.SuperAppAuth||!SuperAppAuth.isConfigured()){button.disabled=true;setMessage(message,'Homologação não configurada.','error');return}try{const session=await SuperAppAuth.getSession();if(!session)return;const profile=await SuperAppAuth.getProfile();adminCurrentUserId=profile?.user_id||'';showAuthenticated(profile,await SuperAppAuth.getEntitlements())}catch(error){SuperAppAuth.logAuthFailure?.(error,'portal-session');setMessage(message,SuperAppAuth.getSafeAuthMessage(error,'Não foi possível validar a sessão.'),'error')}}
    loginForm.addEventListener('submit',async event=>{event.preventDefault();button.disabled=true;setMessage(message,'Validando acesso...');try{SuperAppAuth.setRememberLogin(rememberLogin.checked);await SuperAppAuth.signIn(identifier.value.trim(),password.value);const profile=await SuperAppAuth.getProfile();adminCurrentUserId=profile?.user_id||'';showAuthenticated(profile,await SuperAppAuth.getEntitlements());event.target.reset()}catch(error){SuperAppAuth.logAuthFailure?.(error,'portal-login');setMessage(message,SuperAppAuth.getSafeAuthMessage(error,'Acesso negado.'),'error');button.disabled=false}});
    passwordToggle.addEventListener('click',()=>{const mostrar=password.type==='text';password.type=mostrar?'password':'text';passwordToggle.textContent=mostrar?'Mostrar':'Ocultar';passwordToggle.setAttribute('aria-pressed',mostrar?'false':'true');});
    $('logout-button').addEventListener('click',async()=>{await SuperAppAuth.signOut();location.reload()});
    function switchPortalView(view){const next=view==='admin'?adminSection:appsPanel;appsTab.classList.toggle('active',view!=='admin');adminTab.classList.toggle('active',view==='admin');appsTab.setAttribute('aria-selected',view!=='admin'?'true':'false');adminTab.setAttribute('aria-selected',view==='admin'?'true':'false');appsPanel.classList.add('hidden');adminSection.classList.add('hidden');next.classList.remove('portal-view-enter');void next.offsetWidth;next.classList.remove('hidden');next.classList.add('portal-view-enter');if(!matchMedia('(prefers-reduced-motion: reduce)').matches){next.getAnimations().forEach(animation=>animation.cancel());next.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:340,easing:'cubic-bezier(.16,.84,.44,1)'})}}
    appsTab.addEventListener('click',()=>switchPortalView('apps'));adminTab.addEventListener('click',()=>switchPortalView('admin'));
    function switchAdminPanel(panel){const showApps=panel==='apps',next=showApps?adminAppsPanel:adminUsersPanel;adminUsersTab.classList.toggle('active',!showApps);adminAppsTab.classList.toggle('active',showApps);adminUsersTab.setAttribute('aria-selected',showApps?'false':'true');adminAppsTab.setAttribute('aria-selected',showApps?'true':'false');adminUsersPanel.classList.add('hidden');adminAppsPanel.classList.add('hidden');next.classList.remove('admin-subpanel-enter');void next.offsetWidth;next.classList.remove('hidden');next.classList.add('admin-subpanel-enter');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)next.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:260,easing:'cubic-bezier(.16,.84,.44,1)'})}
    adminUsersTab.addEventListener('click',()=>switchAdminPanel('users'));adminAppsTab.addEventListener('click',()=>switchAdminPanel('apps'));
    const adminUsersBody=$('admin-users'),adminMessage=$('admin-message'),adminText=v=>escapeHtml(v==null?'':v);
    function adminChoices(options){return options.map(option=>({value:String(option.value??''),label:String(option.label??'')}))}
    function adminRolesForScope(scope){return adminRoles.filter(role=>scope==='FRANQUIA'?role.scope_kind==='FRANQUIA':role.scope_kind!=='FRANQUIA')}
    function adminSelect(name,options,value,disabled=false){const choices=adminChoices(options);return '<div class="admin-dropdown" data-admin-dropdown="'+adminText(name)+'"><button class="admin-inline-select" type="button" aria-haspopup="listbox" aria-expanded="false" data-admin-value="'+adminText(value||'')+'" '+(disabled?'disabled':'')+'><span class="admin-select-label">'+adminText(choices.find(option=>option.value===String(value||''))?.label||'Selecione')+'</span><span class="admin-select-chevron" aria-hidden="true">⌄</span></button><div class="admin-dropdown-menu" role="listbox">'+choices.map(option=>'<button class="admin-dropdown-option" type="button" role="option" data-value="'+adminText(option.value)+'" data-label="'+adminText(option.label)+'" '+(option.value===String(value||'')?'aria-selected="true"':'')+'>'+adminText(option.label)+'</button>').join('')+'</div></div>'}
    function adminDropdown(row,name){return row.querySelector('[data-admin-dropdown="'+name+'"]')}
    function adminValue(row,name){return adminDropdown(row,name)?.querySelector('[data-admin-value]')?.dataset.adminValue||''}
    function setAdminDropdown(row,name,options,value,disabled=false){const dropdown=adminDropdown(row,name);if(!dropdown)return;const choices=adminChoices(options),trigger=dropdown.querySelector('[data-admin-value]');trigger.dataset.adminValue=String(value||'');trigger.disabled=disabled;trigger.querySelector('.admin-select-label').textContent=choices.find(option=>option.value===String(value||''))?.label||'Selecione';dropdown.querySelector('.admin-dropdown-menu').innerHTML=choices.map(option=>'<button class="admin-dropdown-option" type="button" role="option" data-value="'+adminText(option.value)+'" data-label="'+adminText(option.label)+'" '+(option.value===String(value||'')?'aria-selected="true"':'')+'>'+adminText(option.label)+'</button>').join('')}
    function positionAdminDropdown(dropdown){const trigger=dropdown.querySelector('.admin-inline-select'),menu=dropdown.querySelector('.admin-dropdown-menu');if(!trigger||!menu)return;const rect=trigger.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(rect.left,window.innerWidth-menu.offsetWidth-8))+'px';menu.style.top=(rect.bottom+6)+'px';menu.style.minWidth=Math.max(rect.width,180)+'px'}
    function bindAdminDropdown(row,name,onChange){const dropdown=adminDropdown(row,name);if(!dropdown||dropdown.dataset.bound)return;dropdown.dataset.bound='true';const trigger=dropdown.querySelector('.admin-inline-select');trigger.addEventListener('click',()=>{document.querySelectorAll('.admin-dropdown.is-open').forEach(item=>{if(item!==dropdown)item.classList.remove('is-open')});dropdown.classList.toggle('is-open');trigger.setAttribute('aria-expanded',dropdown.classList.contains('is-open')?'true':'false');if(dropdown.classList.contains('is-open'))requestAnimationFrame(()=>{positionAdminDropdown(dropdown);const menu=dropdown.querySelector('.admin-dropdown-menu');if(menu&&!matchMedia('(prefers-reduced-motion: reduce)').matches){menu.getAnimations().forEach(animation=>animation.cancel());menu.animate([{opacity:0,transform:'translateY(-10px) scale(.96)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:260,easing:'cubic-bezier(.16,.84,.44,1)'})}})});dropdown.addEventListener('click',event=>{const option=event.target.closest('.admin-dropdown-option');if(!option)return;trigger.dataset.adminValue=option.dataset.value||'';trigger.querySelector('.admin-select-label').textContent=option.dataset.label||'Selecione';dropdown.querySelectorAll('.admin-dropdown-option').forEach(item=>item.setAttribute('aria-selected',item===option?'true':'false'));dropdown.classList.remove('is-open');trigger.setAttribute('aria-expanded','false');onChange?.(trigger.dataset.adminValue)});}
    document.addEventListener('click',event=>{if(!event.target.closest('.admin-dropdown'))document.querySelectorAll('.admin-dropdown.is-open').forEach(item=>item.classList.remove('is-open'))});
    const repositionOpenAdminDropdowns=()=>document.querySelectorAll('.admin-dropdown.is-open').forEach(positionAdminDropdown);
    window.addEventListener('resize',repositionOpenAdminDropdowns);
    window.addEventListener('scroll',repositionOpenAdminDropdowns,true);
    function configureAdminRow(row,user){
      const saveButton=row.querySelector('[data-admin-save]'),isCurrent=user.user_id===adminCurrentUserId;
      function markDirty(){if(!isCurrent){row.classList.add('admin-row-dirty');saveButton.disabled=false}}
      function refreshEntity(){const scope=adminValue(row,'scope'),roleCode=adminValue(row,'role'),role=adminRoles.find(item=>item.code===roleCode),options=scope==='FRANQUIA'?[{value:'',label:'Selecione a franquia'},...adminFranchises.map(item=>({value:item.id,label:item.display_name}))]:role?.scope_kind==='UNIT'?[{value:'',label:'Selecione a unidade'},...adminUnits.map(item=>({value:item.id,label:item.name}))]:[{value:'',label:'Matriz · acesso global'}];setAdminDropdown(row,'entity',options,scope==='FRANQUIA'?user.franchise_id:role?.scope_kind==='UNIT'?user.unit_id:'',isCurrent||(scope==='MATRIZ'&&role?.scope_kind==='GLOBAL'));bindAdminDropdown(row,'entity',markDirty)}
      function refreshRole(){const scope=adminValue(row,'scope'),options=adminRolesForScope(scope).map(role=>({value:role.code,label:role.code+' · '+role.display_name})),current=options.some(option=>option.value===user.role_code)?user.role_code:(options[0]?.value||'');setAdminDropdown(row,'role',options,current,isCurrent);bindAdminDropdown(row,'role',()=>{refreshEntity();markDirty()});refreshEntity()}
      bindAdminDropdown(row,'scope',()=>{refreshRole();markDirty()});bindAdminDropdown(row,'role',()=>{refreshEntity();markDirty()});refreshEntity();
      saveButton?.addEventListener('click',async()=>{const scope=adminValue(row,'scope'),role=adminRoles.find(item=>item.code===adminValue(row,'role')),entity=adminValue(row,'entity'),unitId=scope==='MATRIZ'&&role?.scope_kind==='UNIT'?entity:'',franchiseId=scope==='FRANQUIA'?entity:'';if(!role||(scope==='FRANQUIA'&&!franchiseId)||(role?.scope_kind==='UNIT'&&!unitId)){setMessage(adminMessage,'Selecione o perfil e a unidade ou franquia exigida.','error');return}saveButton.disabled=true;saveButton.textContent='Salvando…';try{await SuperAppAuth.adminAssignAccess(user.user_id,role.code,scope,unitId,franchiseId);setMessage(adminMessage,'Acesso de '+user.display_name+' atualizado e auditado.','success');await loadAdmin()}catch(error){setMessage(adminMessage,error.message||'Operação negada.','error');saveButton.disabled=false;saveButton.textContent='Salvar'}});
      row.querySelector('[data-admin-deactivate]')?.addEventListener('click',async event=>{if(!confirm('Desativar este usuário?'))return;event.currentTarget.disabled=true;try{await SuperAppAuth.adminDeactivateUser(user.user_id);setMessage(adminMessage,'Usuário desativado.','success');await loadAdmin()}catch(error){setMessage(adminMessage,error.message||'Operação negada.','error');event.currentTarget.disabled=false}});
    }
    function renderAdminUsers(){adminUsersBody.innerHTML=adminUsers.map(user=>{const scope=user.scope_kind==='FRANQUIA'?'FRANQUIA':'MATRIZ',status=user.profile_active&&user.binding_active,isCurrent=user.user_id===adminCurrentUserId,roleOptions=adminRolesForScope(scope).map(role=>({value:role.code,label:role.code+' · '+role.display_name}));return '<tr data-admin-user="'+adminText(user.user_id)+'" class="'+(isCurrent?'admin-current-row':'')+'"><td><strong>'+adminText(user.display_name)+'</strong><small>'+adminText(user.login_identifier)+'</small></td><td>'+adminSelect('scope',[{value:'MATRIZ',label:'Matriz'},{value:'FRANQUIA',label:'Franquia'}],scope,isCurrent)+'</td><td>'+adminSelect('role',roleOptions,user.role_code,isCurrent)+'</td><td>'+adminSelect('entity',[], '', false)+'</td><td><span class="status-dot '+(status?'on':'off')+'">'+(status?'Ativo':'Inativo')+'</span></td><td><div class="admin-row-actions">'+(isCurrent?'<span class="current-label">Usuário atual</span>':'<button class="table-action save" type="button" data-admin-save disabled>Salvar</button><button class="table-action danger" type="button" data-admin-deactivate>Desativar</button>')+'</div></td></tr>'}).join('');adminUsers.forEach(user=>{const row=adminUsersBody.querySelector('[data-admin-user="'+CSS.escape(user.user_id)+'"]');if(row)configureAdminRow(row,user)})}
    function renderAdminAppPermissions(){
      const roles=[...adminRoles].sort((a,b)=>a.display_name.localeCompare(b.display_name,'pt-BR')),apps=[...new Map(adminAppPermissions.map(item=>[item.app_code,{code:item.app_code,name:item.app_display_name}])).values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')),permissionMap=new Map(adminAppPermissions.map(item=>[item.app_code+'|'+item.role_code,Boolean(item.can_view)]));
      adminAppPermissionsHead.innerHTML='<tr><th>Aplicativo</th>'+roles.map(role=>'<th><strong>'+adminText(role.code)+'</strong><small>'+adminText(role.display_name)+'</small></th>').join('')+'</tr>';
      adminAppPermissionsBody.innerHTML=apps.length?apps.map(app=>'<tr data-permission-app="'+adminText(app.code)+'"><td><strong>'+adminText(app.name)+'</strong><small>'+adminText(app.code)+'</small></td>'+roles.map(role=>{const checked=permissionMap.get(app.code+'|'+role.code)===true,label='Permitir '+role.display_name+' acessar '+app.name;return '<td><label class="permission-check" title="'+adminText(label)+'"><input type="checkbox" data-app-code="'+adminText(app.code)+'" data-role-code="'+adminText(role.code)+'" aria-label="'+adminText(label)+'" '+(checked?'checked':'')+'><span aria-hidden="true"></span></label></td>'}).join('')+'</tr>').join(''):'<tr><td colspan="'+Math.max(roles.length+1,1)+'" class="permission-empty">Nenhum aplicativo ativo encontrado.</td></tr>';
      adminAppPermissionsBody.onchange=async event=>{const checkbox=event.target.closest('input[data-app-code][data-role-code]');if(!checkbox)return;const appCode=checkbox.dataset.appCode,roleCode=checkbox.dataset.roleCode,nextValue=checkbox.checked,row=checkbox.closest('tr');checkbox.disabled=true;row?.classList.add('permission-saving');setMessage(adminAppsMessage,'Salvando permissão…');try{await SuperAppAuth.adminSetAppRolePermission(appCode,roleCode,nextValue);const record=adminAppPermissions.find(item=>item.app_code===appCode&&item.role_code===roleCode);if(record)record.can_view=nextValue;setMessage(adminAppsMessage,'Permissão atualizada e registrada na auditoria.','success');renderApps(await SuperAppAuth.getEntitlements())}catch(error){checkbox.checked=!nextValue;setMessage(adminAppsMessage,error.message||'Não foi possível atualizar a permissão.','error')}finally{checkbox.disabled=false;row?.classList.remove('permission-saving')}};
    }
    async function loadAdminPermissions(){adminAppPermissions=await SuperAppAuth.adminListAppRolePermissions();renderAdminAppPermissions()}
    async function loadAdmin(){adminUsers=await SuperAppAuth.adminListUsers();renderAdminUsers()}
    function applyTheme(theme){const dark=theme==='dark';document.documentElement.dataset.theme=dark?'dark':'light';themeToggles.forEach(toggle=>{toggle.setAttribute('aria-pressed',dark?'true':'false');toggle.setAttribute('aria-label',dark?'Ativar modo claro':'Ativar modo escuro');const knob=toggle.querySelector('.knob');if(knob)knob.textContent=dark?'🌙':'☀️'});document.querySelector('meta[name="theme-color"]')?.setAttribute('content',dark?'#15171B':'#EEF0F2')}
    themeToggles.forEach(toggle=>toggle.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('321modular_theme',next)}catch(_){}applyTheme(next)}));
    async function initAdmin(){try{[adminUsers,adminRoles,adminFranchises,adminUnits]=await Promise.all([SuperAppAuth.adminListUsers(),SuperAppAuth.adminListRoles(),SuperAppAuth.adminListFranchises(),SuperAppAuth.adminListUnits()]);$('admin-refresh').onclick=loadAdmin;$('admin-apps-refresh').onclick=async()=>{try{await loadAdminPermissions();setMessage(adminAppsMessage,'Permissões atualizadas.','success')}catch(error){setMessage(adminAppsMessage,error.message||'Não foi possível carregar as permissões.','error')}};renderAdminUsers();try{await loadAdminPermissions()}catch(error){setMessage(adminAppsMessage,error.message||'Não foi possível carregar as permissões dos aplicativos.','error')}}catch(error){setMessage(adminMessage,error.message||'Não foi possível carregar a administração.','error')}}
    window.addEventListener('load',()=>{applyTheme(document.documentElement.dataset.theme||'light');rememberLogin.checked=SuperAppAuth?.isRememberLoginEnabled?.()||false;showSession()});
  